#title: AVERtek # your name photo (or website title) here
logo1: "/images/avenidaPDlogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>POWERFUL BREADCRUMB MARKETING; Leverage storytelling links to new adventures; Show your community's resort lifestyle; Time is right to change the old castle for a new one</b> <br>
    3D IMAGE use pointer to rotate, spin; Use zoom to scale the Fairytale Story
  <br><br> 
  <b>ROMANCE WITH ACTUAL COMMUNITY IMAGES/EVENTS - Augmented Reality (AR) transports the story so the Prospect remembers your experience!:</b> <br>
  <br><br>
  <a href="https://avertek.net/xr-now-company-promotion"><b><u>LINK TO EXCITING STORIES/CONTENT</u></b>- Help Prospects visualize a wonderful new life</a> 
  <br><br>
  <a href="https://avertek.net/narrative"><b><u>SHARE TESTIMONIALS</u></b>- Meet fun/friendly residents; Neighbors just like them</a>
  <br><br>
  <a href="https://avertek.net/contact-us"><b><u>COME VISIT OUR FAIRYTALE CASTLE</u></b>- Invite them for a VIP tour to receive a special gift</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
