#title: AVERtek # your name photo (or website title) here
logo1: "/images/avenidaPDlogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>BEGIN STORYTELLING BREADCRUMB LINKS - View 3D Image:</b> <br>
    Use Pointer to rotate, spin; Use zoom to scale
  <br><br> 
  <b>ROMANCE YOUR COMMUNITY - Also View in Augmented Reality (AR):</b> <br>
  <br><br>
  <a href="https://avertek.net/xr-now-company-promotion"><b><u>LINK TO EXCITING CONTENT</u></b>- Our Company's Story/Culture</a> 
  <br><br>
  <a href="https://avertek.net/narrative"><b><u>SHARE TESTIMONIALS</u></b>- See Our Story/Testimonial</a>
  <br><br>
  <a href="https://avertek.net/contact-us"><b><u>COME VISIT US</u></b>- Contact Us for a VIP Tour; Receive a Special Gift</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
