#title: AVERtek # your name photo (or website title) here
logo1: "/images/avenidaPDlogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>POWERFUL BREADCRUMB MARKETING WITH STORYTELLING LINKS</b> <br>
    3D IMAGE use pointer to rotate, spin; Use zoom to scale the Fairytale Story
  <br><br> 
  <b>ROMANCE ACTUAL COMMUNITY IMAGES/EVENTS</b> <br>
   Augmented Reality (AR) transports the story so Prospects remember!
  <br><br>
  <a href="https://avertek.net/xr-now-apartments"><b><u>LINK TO EXCITING STORIES/CONTENT</u></b>- Help Prospects visualize a new life</a> 
  <br><br>
  <a href="https://youtu.be/5YSBRmMTybU"><b><u>SHARE TESTIMONIALS</u></b>- Meet fun/friendly residents just like them</a>
  <br><br>
  <a href="https://avertek.net/contact-us"><b><u>COME VISIT OUR FAIRYTALE CASTLE</u></b>- Invitation for a VIP tour & special gift</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
